# Generated by Django 5.0.3 on 2024-03-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_end_position_name_start_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end',
            name='position_name',
            field=models.CharField(default='----', max_length=100),
        ),
        migrations.AlterField(
            model_name='start',
            name='position_name',
            field=models.CharField(default='----', max_length=100),
        ),
    ]
