# Generated by Django 5.0.3 on 2024-04-12 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_end_position_name_alter_start_position_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_active', models.BooleanField(default=False)),
                ('delivery_start', models.FloatField(default=0.0, max_length=16)),
                ('delivery_end', models.FloatField(default=0.0, max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='operator',
            name='ending_point',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='starting_point',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='user',
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_end', to='core.delivery')),
                ('relative_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_start', to='core.delivery')),
            ],
        ),
        migrations.DeleteModel(
            name='End',
        ),
        migrations.DeleteModel(
            name='Start',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
    ]
