# Generated by Django 5.0.3 on 2024-04-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_position_delivery_delivery_e_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='address',
            field=models.CharField(default='----', max_length=256),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='lat',
            field=models.FloatField(default=0.0, max_length=25),
        ),
        migrations.AlterField(
            model_name='position',
            name='long',
            field=models.FloatField(default=0.0, max_length=25),
        ),
    ]
