# Generated by Django 5.0.3 on 2024-04-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_position_address_alter_delivery_id_alter_operator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='e_lat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_lat', to='core.position', to_field='lat'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='e_long',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e_long', to='core.position', to_field='long'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='s_lat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_lat', to='core.position', to_field='lat'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='s_long',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='s_long', to='core.position', to_field='long'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='now_lat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='now_lat', to='core.position', to_field='lat'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='now_long',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='now_long', to='core.position', to_field='long'),
        ),
        migrations.AlterField(
            model_name='position',
            name='lat',
            field=models.FloatField(default=0.0, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='long',
            field=models.FloatField(default=0.0, max_length=25, unique=True),
        ),
    ]
