# Generated by Django 5.0.3 on 2024-04-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_delivery_e_lat_alter_delivery_e_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='delivery_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to='core.delivery'),
        ),
    ]
