# Generated by Django 5.0.3 on 2024-04-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_operator_delivery_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='now_lat',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='now_long',
        ),
        migrations.AddField(
            model_name='operator',
            name='n_lat',
            field=models.FloatField(default=0.0, max_length=25),
        ),
        migrations.AddField(
            model_name='operator',
            name='n_long',
            field=models.FloatField(default=0.0, max_length=25),
        ),
    ]
